### ISSUE TITLE
primus-checks ELF64-ubuntu18.04-gui UNIX-System V other

### ISSUE THREAD

**Issue by Soapmaze** [BinaryAnalysisPlatform/bap-toolkit#3]
1. What incidents are expected to be reported, in case of a false negative, or what incidents are reported but are not expected? What are the presumed locations of the weaknesses in the binary?
-An attempt was made to analyze a binary with a CWE-125 vulnerability, but the vulnerability was not found. I tried to detect using primus-checks, but the bar did not run and the results of extension halt were only printed in the inserts file and ended.
![primus-checks_command_results](https://user-images.githubusercontent.com/21697914/88746101-adcdf400-d186-11ea-9dd7-8dd77e2dae6d.png)

2. Upload the binary if possible.
[cwe_125_bin.zip](https://github.com/BinaryAnalysisPlatform/bap-toolkit/files/4991987/cwe_125_bin.zip)
Source Code
[cwe_125_source.zip](https://github.com/BinaryAnalysisPlatform/bap-toolkit/files/4991988/cwe_125_source.zip)

3.  Upload all files generated by the check, i.e., `log` files, `incidents`, `stdout`, `stderr`, etc (some may be missing depending on a tool)
incidents
[incidents.zip](https://github.com/BinaryAnalysisPlatform/bap-toolkit/files/4991992/incidents.zip)
log
[log.zip](https://github.com/BinaryAnalysisPlatform/bap-toolkit/files/4991995/log.zip)

Additional Information
=================
1. The output of the following commands:
bap --version
[bap_version.txt](https://github.com/BinaryAnalysisPlatform/bap-toolkit/files/4991980/bap_version.txt)
bap --llvm-version
[bap_llvm_version.txt](https://github.com/BinaryAnalysisPlatform/bap-toolkit/files/4991979/bap_llvm_version.txt)
bap list plugins
[bap_list_plugins.txt](https://github.com/BinaryAnalysisPlatform/bap-toolkit/files/4991982/bap_list_plugins.txt)

2. The set of symbols that bap detects in the binary
bap ./binary -dsymbols > binary.symbols
[cwe_125_test_symbols.zip](https://github.com/BinaryAnalysisPlatform/bap-toolkit/files/4991986/cwe_125_test_symbols.zip)

**Comment by ivg** [comment]
Thanks for the report. The reason why the analysis doesn't even start is the https://github.com/BinaryAnalysisPlatform/bap/issues/1124 bug in 2.1.0 so you have to [update][1] to the latest version of bap (2.2.0~alpha) to enable it. But the weakness itself still won't be detected since right now we don't have an analysis that detects stack-based buffer overflows. We can only detect some class of the heap-based buffer overflows. We are working on stack-based overflows right now, so watch for updates.

[1]: https://github.com/BinaryAnalysisPlatform/bap/wiki/Build-tips-and-tricks#getting-latest-development-version
